openapi: 3.0.3
info:
  title: User Management Service
  description: |
    The User Management Service allows the management of external users and
    their permissions within the WISdoM platform.
    It uses an external OpenID Connect Provider.
  version: 1.0.0
servers:
  - url: '/api/auth/'
    description: Default Path

tags:
  - name: Session Management
    description: |
      Routes in this category are used to manage sessions and allow users to
      login and log out as well as creating long-living credentials and external
      clients
  - name: Permission Management
    description: |
      Routes in this category are used to grant or revoke access privileges for
      individual services on a user basis
  - name: Others
    description: |
      Routes in this category are used for miscellaneous tasks such as discovery
      of resources and providing resources
paths:
  /.well-known/jwks.json:
    get:
      summary: JSON Web Key Set
      tags:
        - Others
      description: |
        Retrieve the JSON Web Key Set used to validate JSON Web Tokens issued
        by the user management
      externalDocs:
        description: RFC 7517 (JSON Web Key (JWK))
        url: https://www.rfc-editor.org/rfc/rfc7517
      responses:
        200:
          description: JSON Web Key Set
          content:
            application/json:
              schema:
                type: object
                properties:
                  keys:
                    type: array
                    items:
                      type: object
                      properties:
                        kty:
                          type: string
                        crv:
                          type: string
                        x:
                          type: string
                        y:
                          type: string
                        use:
                          type: string
                        kid:
                          type: string
                        n:
                          type: string
                        e:
                          type: string
                        alg:
                          type: string
              example:
                keys:
                  - kty: EC
                    crv: P-256
                    x: MKBCTNIcKUSDii11ySs3526iDZ8AiTo7Tu6KPAqv7D4
                    'y': 4Etl6SRW2YiLUrN5vfvVHuhp7x8PxltmWWlbbM4IFyM
                    use: enc
                    kid: '1'
                  - kty: RSA
                    'n': >-
                      0vx7agoebGcQSuuPiLJXZptN9nndrQmbXEps2aiAFbWhM78LhWx4cbbfAAtVT86zwu1RK7aPFFxuhDR1L6tSoc_BJECPebWKRXjBZCiFV4n3oknjhMstn64tZ_2W-5JsGY4Hc5n9yBXArwl93lqt7_RN5w6Cf0h4QyQ5v-65YGjQR0_FDW2QvzqY368QQMicAtaSqzs8KJZgnYb9c7d0zgdAZHzu6qMQvRL5hajrn1n91CbOpbISD08qNLyrdkt-bFTWhAI4vMQFh6WeZu0fM4lFd2NcRwr3XPksINHaQ-G_xBniIqbw0Ls1jF44-csFCur-kEgU8awapJzKnqDKgw
                    e: AQAB
                    alg: RS256
                    kid: '2011-04-29'

