openapi: 3.0.3
info:
  title: User Management Service
  description: |
    The User Management Service allows the management of external users and
    their permissions within the WISdoM platform.
    It uses an external OpenID Connect Provider.
  version: 1.0.0
servers:
  - url: '/api/auth/'
    description: Default Path

tags:
  - name: Session Management
    description: |
      Routes in this category are used to manage sessions and allow users to
      login and log out as well as creating long-living credentials and external
      clients
  - name: Permission Management
    description: |
      Routes in this category are used to grant or revoke access privileges for
      individual services on a user basis
  - name: Others
    description: |
      Routes in this category are used for miscellaneous tasks such as discovery
      of resources and providing resources
paths:
  

  
